### ISSUE TITLE
upload d'un shp en BD

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#1]

**Comment by khameos** [comment]
Ajout d'un import de ZIP avec shp/shx/dbf/prj dans openLib en BDD postgis

Dans le prj => projection

**Comment by khameos** [comment]
Une fois que le fichier est dé-Zippé et mis en BDD. Je conserve les fichiers déZippés ou je supprime ?
(ca peut prendre de l'espace disque à force)

**Comment by JBL034** [comment]
SUPER !!! j'ai fait un test sur Mali, ça marche bien.
pour le moment on garde les zip sur le serveur je pense, si on a de la place.

**Comment by JBL034** [comment]
mon test 
![image](https://user-images.githubusercontent.com/31103023/32141922-6c93c558-bc8c-11e7-84d4-6a6dad8c6997.png)
