### ISSUE TITLE
upload shp

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#11]
si absence de du fichier .prj-->message d'avertissement
si la l'EPSG non valide--> message "votre projection n'est pas reconnue par e-DP. Veuillez réessayer avec une autre projection".

**Comment by khameos** [comment]
J'ai testé tous les fichiers ZIP : 
- brln => manque le .prj
- chef_lieux => ok avec srid = 3785
- limites_district => ok avec srid = 3857
- courbes_niveaux => ok avec srid = 4326
- limite_commune => ok avec srid = 4326
- pedologie_lac => ok avec srid = 3785
- vegetation => ok avec srid = 3785

**Comment by JBL034** [comment]
Ok, je vais regarder

 

De : khameos [mailto:notifications@github.com] 
Envoyé : mardi 12 décembre 2017 14:32
À : Khameos-JBL/e-watch <e-watch@noreply.github.com>
Cc : JBL034 <jean-baptiste.laurent@cirad.fr>; Author <author@noreply.github.com>
Objet : Re: [Khameos-JBL/e-watch] upload shp (#11)

 

J'ai testé tous les fichiers ZIP :

*	brln => manque le .prj
*	chef_lieux => ok avec srid = 3785
*	limites_district => ok avec srid = 3857
*	courbes_niveaux => ok avec srid = 4326
*	limite_commune => ok avec srid = 4326
*	pedologie_lac => ok avec srid = 3785
*	vegetation => ok avec srid = 3785

**Comment by khameos** [comment]
Il faut que je gère les performances maintenant sur des SHP aussi gros !
c'est trop lent pour le moment

**Comment by khameos** [comment]
En "simplifiant" la précision, le résultat est identique mais les chargements plus rapide 
(update shp_46 set geom = st_simplify(shp_46.geom, 0.001::double precision))
Reste à le mettre en place sur tous les upload !
http://ns3036890.ip-149-202-208.eu/e-dp/admin/seeShp/46
