### ISSUE TITLE
ressources partagées

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#15]
mettre un outil de recherche multi-critères en haut de la page

**Comment by khameos** [comment]
1ère ébauche mise en place

A améliorer avec pagination, etc ...

**Comment by JBL034** [comment]
Pas mal du tout.

Tu continues ? ;-)

 

De : khameos [mailto:notifications@github.com] 
Envoyé : jeudi 14 décembre 2017 17:59
À : Khameos-JBL/e-watch <e-watch@noreply.github.com>
Cc : JBL034 <jean-baptiste.laurent@cirad.fr>; Author <author@noreply.github.com>
Objet : Re: [Khameos-JBL/e-watch] ressources partagées (#15)

 

1ère ébauche mise en place
