### ISSUE TITLE
téléchargement depuis 'Cartographie'

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#18]
je click sur l'icone en bas à gauche (Morondava):

![image](https://user-images.githubusercontent.com/31103023/34489509-ee3a84ba-efdc-11e7-9768-4f36f40b8676.png)

**Comment by khameos** [comment]
https://github.com/Khameos-JBL/e-watch/issues/13

c'est suite au changement de nom : les anciens fichiers ne marchent plus (c'est normal)

**Comment by khameos** [comment]
j'ai passé une requête pour pas avoir à effacer les docs ;)
