### ISSUE TITLE
difficile !

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#24]
... mais important ;-)

la plupart des données dans les dP sont contenus dans des fichiers Excel.
mais il y a souvent plusieurs onglets... Il faudrait donc dans une ressource créée pouvoir mettre n fichiers...

**Comment by JBL034** [comment]
exemple sur ce fichier qu'on connait bien...
[grosproducteurs_2011.xlsx](https://github.com/Khameos-JBL/e-watch/files/1613036/grosproducteurs_2011.xlsx)

**Comment by khameos** [comment]
Sur "Mon E-dP" => voir Producteurs 2011-2012

Fichier XLS uploadé + création des onglets en CSV OK

**Comment by khameos** [comment]
Il reste à voir l'affichage des données dans Ressources partagées !

**Comment by khameos** [comment]
Dans RP :

**Comment by khameos** [comment]
Dans RP : 
- si doc n'est pas en BDD => l'image permet de télécharger le DOC
- si doc en BDD => l'image permet de voir le doc en BDD + ajout d'un lien pour télécharger

Ca te convient ?
