### ISSUE TITLE
Gestion des Publi

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#25]
une demande récurente: gérer les liste bibliographie scientifique au sain d'un dp.
pour le moment, elles sont gérées dans leur CMS: https://www.dp-spad.org/productions/articles/2015
on devrait pouvoir faire mieux !

dans un premier temps, on devrait s'en sortir
du coup il faudrait juste ajouter une zone 'lien externe', comme sur open-lib, pour faire le lien vers l'éditeur de l'article.
ajouter aussi dans la page des ressources partgagées, une sélection sur l'année (de début).

**Comment by khameos** [comment]
Ajout recherche sur l'année => OK, livré

**Comment by khameos** [comment]
ajout lien externe
