### ISSUE TITLE
Recherche dans les tables

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#31]
Maintenant que les données sont en BDD, on peut réfléchir à un méga moteur de recherche:
rechercher une occurence dans toutes les tables issues des CSV... (l'équivalent du moteur GSA de Open Lib, mais dans les tables)

possible pour Khaméos ? (je connais la réponse...).
ce sera ça notre vrai valeur ajoutée !

**Comment by khameos** [comment]
Ca devrait même être rapide à mettre en place ;)
