### ISSUE TITLE
URGENT: taille de description

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#39]
la zone descritpion est Varchar 255 il faudrait le mettre en long char (ou autre), mais ça risque d'être short pour ma présentation de demain.
Tu testes éventuellement en local ? (ou si tu as le courrage ce dimance ;-) )

**Comment by JBL034** [comment]
en provisoire, mettre un message lors de la saisie en BO si le texte saisi dans Description dépagge 255. Actuellement ça fait planter et on perd sa saisie sans savoir pourquoi, donc les users vont recommencer la même saisie, etc etc...

**Comment by khameos** [comment]
je l'ai passé en text => ca devrait résoudre les problèmes
