### ISSUE TITLE
Régions/Districts

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#43]
en sélectionnant les régions:

Sava 
Analanjirofo 
Sofia 
Boeny

on devrait avoir (entre autre) les districts:

Vavatenina 
Soanierana 
Ivongo 
Andapa 
Bealanana 
Marovoay

mais il en manque...

**Comment by khameos** [comment]
A part Ivongo, j'ai tout les autres

**Comment by khameos** [comment]
Et dans refcommunes, il n'y a pas de district Ivongo
