### ISSUE TITLE
mise en place d'une nouvelle charte graphique

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#7]
inspirée de VCA, avec en plus une partie publique (web) pour diffusion des données

**Comment by JBL034** [comment]
on peut aussi acheter un thème Boostrap, j'ai le busget.
qq exemples:
- https://themes.getbootstrap.com/products/application
- https://www.templatemonster.com/fr/modeles-de-sites-web-bootstrap/
- pas mal celui là: http://gt3demo.com/html/timber/?_ga=2.251615106.527876583.1511171576-904192164.1511171576

**Comment by khameos** [comment]
Je l'ai retrouvé !
http://template.accent.itembridge.com/demo-2.html
