### ISSUE TITLE
Modif des attributs

### ISSUE THREAD

**Issue by JBL034** [Khameos-JBL/e-watch#9]
pouvoir revenir sur une 'fiche' de mon e-dP en modification

**Comment by khameos** [comment]
On peut éditer un document mais pas le fichier uploadé (que faire si le CSV/SHP sont en BDD?)

**Comment by JBL034** [comment]
c'est éditer les Méto données dont je parlais (comme tu as fait d'ailleur !).

**Comment by JBL034** [comment]
je clos ?
